FROM node:alpine AS dependencies

WORKDIR /usr/src/app

RUN chown -R node:node .

USER node

COPY --chown=node:node package*.json ./

RUN npm i

COPY --chown=node:node ./ ./

ARG REACT_APP_BACKEND_WS

ARG REACT_APP_BACKEND_URL

RUN CI=true npm test