apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  ALLOWED_ORIGIN: http://frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
      app: backend
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080 
    - name: websocket
      protocol: TCP
      port: 3585
      targetPort: 3585 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  replicas: 2
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nathapaulino/backend-chatapp
        ports:
        - containerPort: 8080
        - containerPort: 3585
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets